### ISSUE TITLE
Cloudmesh-GPU not working on Rivanna

### ISSUE THREAD

**Issue by rknuu** [Data-ScienceHub/mlcommons-science#50]
- [x] Need to research into why the Gpu().system() call is returning `None` on Rivanna.
- [x] add gpu count in API and commandline
- [ ] (Robert) always rerun an array even if there is only one GPU.
- [ ] (Robert)verify if we can use cloudmesh Printer.flatwrite, or Printer.attribute in some fashion to write things, maybe we need to modify the yable print functionality ...
- [ ] (Robert) check on rivanna

**Comment by rknuu** [comment]
Found the issue with cloudmesh-gpu: it doesn't appear to handle multiple gpu systems.  When dropping extra parameters from the `smi(output="json")` call, the attribute loop assumes that result is a dictionary and not a list of dictionaries.  I'm working in some logic to handle that scenario now.

**Comment by laszewsk** [comment]
maybe we can also add a def __str__() that prints it out in a nice format. The Printer.write can handle lists and dicts but assumes pretty much flat structure. I have also a flatdict feature in cloudmesh, so that iv dicts are nested we can simply apply flatdict and it creates . separated keys, then we can just use Printer.write.

**Comment by laszewsk** [comment]
I merged our codes. Due to a conflict, please can you confirm. e.g. i added a strip to the vendor. 

Also I think we want to always return an array, even if we only have one gpu. I had no time to look into what you implemented. 
This way it is consistent ...
We want to add a property

gpu.count 

so we find out how many gpus are in the system

**Comment by laszewsk** [comment]
I added counter command and api templet. PLease can you complete and set the number in gpu.count

**Comment by laszewsk** [comment]
I implemented a maybe not so elegant way, but it works on one processor machine, can you check on rivanna
